SELECT * FROM Users;
SELECT * FROM Products;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;

-- solutions

-- 1. List all customers who have made purchases of more than $80.

SELECT U.name, O.total_amount
FROM Users U
INNER JOIN Orders O
ON U.user_id = O.user_id
WHERE O.total_amount > 80;

-- 2. Retrieve all orders placed in the last 280 days along with the customer name and email.

SELECT 
    U.name AS customer_name,
    U.email
FROM Orders O
JOIN Users U ON O.user_id = U.user_id
WHERE O.order_date >= CURDATE() - INTERVAL 280 DAY;

-- 3. Find the average product price for each category.

SELECT category, avg(price) as 'Average amount by category'
FROM Products
GROUP BY category
ORDER BY avg(price) DESC;

-- 4. List all customers who have purchased a product from the category Electronics.

SELECT U.name, O.order_id, O.user_id, P.product_id, P.name, P.category
FROM Products P
LEFT JOIN OrderDetails OD
ON P.product_id = OD.product_id
JOIN Orders O
ON O.order_id = OD.order_id
JOIN Users U
ON O.user_id = U.user_id
WHERE P.category = "Electronics";

-- 5.	Find the total number of products sold and the total revenue generated for each product.

SELECT OD.product_id, P.name, P.category, sum(OD.quantity) as "Products sold", sum(OD.quantity * P.price) as "Each product revenue"
FROM Products P
RIGHT JOIN OrderDetails OD
ON OD.product_id = P.product_id
GROUP BY OD.product_id;

-- 6.	Update the price of all products in the Books category, increasing it by 10%. Query.

SELECT DISTINCT name, category, ceil(price + (price * 10 / 100)) as "New Price"
FROM products
WHERE category = "Books";

-- 7. Remove all orders that were placed before 2020.

SELECT * FROM Orders
WHERE year(order_date) > 2020;

-- 8. Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.

SELECT U.name, OD.product_id, P.name, OD.quantity, O.order_date
FROM Orders O
LEFT JOIN OrderDetails OD
ON O.order_id = OD.order_id
LEFT JOIN Products P
ON OD.product_id = P.product_id
LEFT JOIN Users U
ON O.user_id = U.user_id
WHERE O.order_date = "2024-05-01";

-- 9. Fetch all customers and the total number of orders they have placed

SELECT U.name, O.user_id, count(OD.order_id) as "Total Orders"
FROM Orders O
LEFT JOIN OrderDetails OD
ON O.order_id = OD.order_id
INNER JOIN Users U
ON U.user_id = O.user_id
GROUP BY O.user_id;

-- 10. Retrieve the average rating for all products in the Electronics category.

SELECT P.name, P.category, sum(OD.quantity) as "Total Quantity",
	CASE WHEN sum(OD.quantity) > 5 THEN 5
		 WHEN sum(OD.quantity) < 5 THEN 2.5
		 ELSE 0
	END AS "AVG RATING"
FROM Products P
JOIN OrderDetails OD
ON OD.product_id = P.product_id
GROUP BY P.name, P.category
HAVING P.category = "Electronics";

-- 11. List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.

SELECT P.name, sum(OD.quantity) as "Total Quantity"
FROM Products P
JOIN OrderDetails OD
ON OD.product_id = P.product_id
GROUP BY P.name
HAVING sum(OD.quantity) > 1;

-- 12. Find the total revenue generated by each category along with the category name.

SELECT category, sum(price) as 'Total revenue by category'
FROM Products
GROUP BY category
ORDER BY avg(price) DESC;
